"""Drop item table

Revision ID: 8b28c220b1b5
Revises: a1b2c3d4e5f6
Create Date: 2026-10-06 23:13:08.071475

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b28c220b1b5'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_constraint(op.f('appointment_appointment_number_key'), 'appointment', type_='unique')
    op.drop_constraint(op.f('customer_phone_number_key'), 'customer', type_='unique')
    op.drop_constraint(op.f('invoice_appointment_id_key'), 'invoice', type_='unique')
    op.drop_constraint(op.f('invoice_invoice_number_key'), 'invoice', type_='unique')
    op.drop_constraint(op.f('payment_payment_number_key'), 'payment', type_='unique')
    op.drop_constraint(op.f('quote_quote_number_key'), 'quote', type_='unique')
    op.drop_constraint(op.f('review_appointment_id_key'), 'review', type_='unique')
    op.drop_constraint(op.f('service_name_key'), 'service', type_='unique')
    op.drop_constraint(op.f('technician_user_id_key'), 'technician', type_='unique')
    op.drop_index(op.f('ix_technician_user_id'), table_name='technician')
    op.create_index(op.f('ix_technician_user_id'), 'technician', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technician_user_id'), table_name='technician')
    op.create_index(op.f('ix_technician_user_id'), 'technician', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('technician_user_id_key'), 'technician', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('service_name_key'), 'service', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('review_appointment_id_key'), 'review', ['appointment_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('quote_quote_number_key'), 'quote', ['quote_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('payment_payment_number_key'), 'payment', ['payment_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('invoice_invoice_number_key'), 'invoice', ['invoice_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('invoice_appointment_id_key'), 'invoice', ['appointment_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('customer_phone_number_key'), 'customer', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('appointment_appointment_number_key'), 'appointment', ['appointment_number'], postgresql_nulls_not_distinct=False)
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    # ### end Alembic commands ###
